# Generated by Django 5.2 on 2025-08-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "Мужской"), ("F", "Женский")],
                max_length=1,
                verbose_name="Пол",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
